---
title: "R Notebook"
output: html_notebook
---

```{r}
### IMPORT BIBLIOTEK

library(dplyr)
library(readxl)
library(ggplot2)
library(ggpubr)
library(ggExtra)
library(sf)
library(tmap)
library(tmaptools)


```
```{r}
### ZAD 1: W badaniu udział wzięło …………… rozwiedzionych osób (zmienna fC11) ODP = 49

zad_1 <- zbior_danych_1 %>% count(zbior_danych_1$fC11==4)
zad_1

```


```{r}
### ZAD 2. Średnia wieku (wiek) rozwiedzionych osób (zmienna fC11) wynosiła ……… lat. ODP = 48,67


rozwiedzione <- zbior_danych_1 %>% filter(fC11==4)
zad_2 <- mean(rozwiedzione$wiek)
zad_2



```


```{r}
### ZAD 3: Mężczyzn (zmienna Plec), z województwa wielkopolskiego (zmienna WOJEWODZTWO) oraz kobiet z województwa podlaskiego udział w badaniu ankietowym wzięło łącznie……………. Odp : 97

m_wlkp <- zbior_danych_1 %>% filter(plec == 1 & WOJEWODZTWO == 30)
k_podlaskie <- zbior_danych_1 %>% filter(plec == 2 & WOJEWODZTWO == 20)
zlicz_m <- count(m_wlkp)
zlicz_k <- count(k_podlaskie)
zad_3 <- zlicz_m + zlicz_k
zad_3



```

```{r}
### ZAD 4: Kobiet (zmienna Plec) z województw (zmienna WOJEWODZTWO), których kod kończy się cyfrą 2, a które jednocześnie mieszkają na wsi (zmienna KLASA_MIEJSOWOSCI) w badaniu ankietowym udział wzięło…………… ODP: 73                                                                                                             
k_wies <- zbior_danych_1 %>% filter(plec == 2 & (WOJEWODZTWO == 2 | WOJEWODZTWO == 12 | WOJEWODZTWO == 22 | WOJEWODZTWO == 32) & KLASA_MIEJSCOWOSCI == 6)
zad_4 <- count(k_wies)
zad_4

```

```{r}
### ZAD 5: Uzupełnij poniższą tabelę krzyżową, w której zawarte są informacje o liczbie respondentów ze względu na ich stan cywilny  (zmienne fC11) i zmienną fp29 (Co jest według Pana/Pani ważniejsze w życiu?)

zad_5 <- table(x=zbior_danych_1$fC11, y = zbior_danych_1$fp29)
zad_5


```


```{r}
### ZAD 6: Dokonaj rekodowania zmiennej fp65 (Pana/Pani własny (osobisty) dochód miesięczny netto (na rękę) średnio z ostatnich trzech miesięcy wyniósł) według następującego schematu: 1 – do 1700 zł włącznie, 2 – powyżej 1700 zł. Następnie uzupełnij poniższą tabelę liczebnościami.   

rekodowanie <- zbior_danych_1 %>% mutate(fp65=case_when(fp65 <= 1700 ~ 1,
                                                  TRUE ~ 2))
zad_6 <- table(x = rekodowanie$plec, y = rekodowanie$fp65)
zad_6

```



```{r}
### ZAD 7: Uzupełnij informację o odsetku respondentów ze względu na ich stan cywilny (zmienna fC11) wpisując odpowiednie wartości nad każdym słupkiem osobno. Stwórz odpowiedni wykres w ggplot2 

ggplot(zbior_danych_1,aes(x=fC11))+ 
  geom_bar(fill = 'green')+
  geom_text(aes(label = scales::percent(..prop..)), stat= "count", vjust = -0.4)
  
```

```{r}
### ZAD 8: Oblicz i zinterpretuj współczynnik korelacji liniowej Pearsona pomiędzy wiekiem  (zmienna wiek) a wagą (zmienna fp56) kobiet (zmienna Plec) zamieszkujących wieś (zmienna KLASA_MIEJSOWOSCI) Pearson = 0,3651897

kobiety_zad_8 <- zbior_danych_1 %>% filter(plec == 2 & KLASA_MIEJSCOWOSCI == 6)
zad_8 <- cor(kobiety_zad_8$wiek, kobiety_zad_8$fp56, method = "pearson")
zad_8



```

```{r}
### ZAD 9: Kwartyle wagi (zmienna fp56) mężczyzn (zmienna Plec) z województwa wielkopolskiego (zmienna WOJEWODZTWO) wynosiły: 1 KW: 80, 20 KW = 85, 3 KW = 94,25

zad_9 <- zbior_danych_1 %>% filter(plec == 1 & WOJEWODZTWO == 30)
summary(zad_9$fp56)



```


```{r}
### ZAD 10: Utwórz nową zmienną telewizor, która przyjmować będzie wartości równe 50% wartości zmiennej: Ile czasu poświęcił Pan przeciętnie dziennie w minionym tygodniu na oglądanie telewizji?  (zmienna fp70). Ile wynosi odchylenie standardowe tak wyznaczonej zmiennej w grupie osób z województwa mazowieckiego (zmienna WOJEWODZTWO)? ODP: 0.594368


tv <- zbior_danych_1 %>% mutate(telewizor = fp70*0.5)
tv_mazowsze <- zad10 %>% filter(WOJEWODZTWO==14)
zad_10 <- sd(tv_mazowsze$telewizor)
zad_10


```
```{r}
### ZAD 11: Napisz funkcję w języku R, która dla dowolnego stożka prostego o wysokości h oraz promieniu podstawy r wyznaczy jego objętość (V), pole podstawy (Pp), pole powierzchni bocznej (Ppb) oraz długość tworzącej stożka (l).

stozek <- function(h, r){
  pp <- pi * r^2
  v <- pp* h * (1/3)
  l <- sqrt(r^2 + h^2)
  pb <- pi * r * l
  print(paste("PP = ", pp, "V = ", v, "L = ",l,"pb = ", pb))
}

stozek(5,5)

```

```{r}
### ZAD 12: Wykorzystując pakiet dplyr oblicz średnią i odchylenie standardowe wieku (zmienna wiek) dla osób mieszkających w województwie mazowieckim (zmienna WOJEWODZTWO). Jako wynik podaj postać napisanego kodu. 

zad_12 <- zbior_danych_1 %>% filter(WOJEWODZTWO == 14) %>% summarise(srednia = mean(wiek, na.rm=TRUE), odchylenie = sd(wiek, na.rm = TRUE))
zad_12


```

```{r}
### ZAD 13: Dana jest macierz A, B oraz C postaci:

a <- matrix(c(3, 1, 2, 4,5,4,3,6,4), nrow = 3, ncol = 3, byrow = TRUE)
b <- matrix(c(3, 1, 2, 1,0,4,2,-3,-2), nrow = 3, ncol = 3, byrow = TRUE)
c <- matrix(c(2,0,5,-1,-7,4, -2,-3,-6), nrow = 3, ncol = 3, byrow = TRUE)

# Oblicz:
# a)	Wyznacznik macierzy A:
det(A) # =2

# b) 	D=(AB^T )^(-1)C:

d1 <- a%*%t(b)
d <- solve(d1) %*% c
d

# c) 	E=A^T+B^(-1)+3C

e <- t(a) + solve(b) + 3*c
e







```

```{r}
### ZAD 14: Utwórz tabelę przedstawiającą średni wiek (zmienna wiek) osób w przekroju stanu cywilnego (zmienna fC11). Zastosuj w tym celu dowolny pakiet języka programowania R

zad_14<- zbior_danych_1  %>% group_by(fC11)%>%summarise_at(vars(wiek), list(name = mean)) 
zad_14



```

```{r}
### ZAD 15: Napisz funkcję, która dla zadanego promienia r zwraca pole (P=πr^2) i obwód koła (Ob=2πr).

kolo <- function(r){
  P = pi * r^2
  Ob = 2 * pi * r
  print(paste("P = ", P, "Ob = ", Ob))
}

kolo(6)


```

```{r}
### ZAD 16: Stwórz kartogram (wykres mapowy) w pakiecie ggplot2 pokazujący średni dochód (zmienna fp65)  w przekroju województw

wojewodztwa <- st_read("Wojewodztwa.shp")
sr_doch <- zbior_danych_1 %>% group_by(WOJEWODZTWO) %>% summarise(srednia = round(mean(fp65),1)) %>% rename(JPT_KOD_JE = WOJEWODZTWO)
wojewodztwa$JPT_KOD_JE <- as.numeric(wojewodztwa$JPT_KOD_JE)
typeof(wojewodztwa$JPT_KOD_JE)
wojewodztwa_all <- left_join(by='JPT_KOD_JE', wojewodztwa, sr_doch)

tm_shape(wojewodztwa_all)+
  tm_polygons(col='srednia',border.col='black', tittle = "średni \n dochod")+
  tm_layout(legend.outside = TRUE, 
            legend.format = list(text.separator='  -  '))+
  tm_text(text='srednia',size=0.7,ymod=-0.7)+
  tm_shape(wojewodztwa_all)+
  tm_text(text='JPT_NAZWA_',size=0.7)


```

